try

diff --git a/.github/actions/auto_versioning/action.yml b/.github/actions/auto_versioning/action.yml
--- a/.github/actions/auto_versioning/action.yml
+++ b/.github/actions/auto_versioning/action.yml
@@ -17,21 +17,18 @@ runs:
       shell: bash
       run: |
         version=$(echo ${{ inputs.previous }} | cut -d 'v' -f2)
-        _segment=${{ inputs.segment }}
         segments=(${version//./ })
 
-        segments[0]=$((segments[0]))
-        segments[1]=$((segments[1]))
-        segments[2]=$((segments[2]))
-
-
-        echo "major: ${segments[0]}"
-        echo "minor: ${segments[1]}"
-        echo "patch: ${segments[2]}"
-
-        ((segments[2]++))
-
-        echo "done if statement"
+        if [[ ${{ inputs.segment }} == 'minor' ]]
+        then
+          segments[1]=$(($segments[1] + 1))
+        elif [[ ${{ inputs.segment }} == 'patch' ]]
+        then
+          segments[2]=$(($segments[2] + 1))
+        else
+          echo "Invalid segment provided. Supported segments are minor or patch."
+          exit 1
+        fi
 
         new_version="v${segments[0]}.${segments[1]}.${segments[2]}"
 
@@ -40,40 +37,6 @@ runs:
         echo "username=$(echo `git log -n 1 --pretty=format:%an`)" >> $GITHUB_OUTPUT
         echo "email=$(echo `git log -n 1 --pretty=format:%ae`)" >> $GITHUB_OUTPUT
         echo "semver=$new_version" >> $GITHUB_OUTPUT
-
-    # - id: versioning
-    #   shell: bash
-    #   run: |
-    #     version=$(echo ${{ inputs.previous }} | cut -d 'v' -f2)
-    #     _segment=${{ inputs.segment }}
-    #     segments=(${version//./ })
-
-    #     echo "major: ${segments[0]}"
-    #     echo "minor: ${segments[1]}"
-    #     echo "patch: ${segments[2]}"
-
-    #     if [[ ${{ inputs.segment }} == 'minor' ]]
-    #     then
-    #       ((segments[1]++))
-    #     elif [[ ${{ inputs.segment }} == 'patch' ]]
-    #     then
-    #       ((segments[2]++))
-    #     else
-    #       echo "Invalid segment provided. Supported segments are minor or patch."
-    #       exit 1
-    #     fi
-
-    #     ((segments[2]++))
-
-    #     echo "done if statement"
-
-    #     new_version="v${segments[0]}.${segments[1]}.${segments[2]}"
-
-    #     echo "new version: $new_version"
-
-    #     echo "username=$(echo `git log -n 1 --pretty=format:%an`)" >> $GITHUB_OUTPUT
-    #     echo "email=$(echo `git log -n 1 --pretty=format:%ae`)" >> $GITHUB_OUTPUT
-    #     echo "semver=$new_version" >> $GITHUB_OUTPUT
 
     - id: push-tags
       shell: bash
