add script

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -26,11 +26,21 @@ jobs:
 
       - name: Install dependencies
         id: install_dependencies
-        run: yarn install 2>&1 | tee error.log
+        run: |
+          yarn install 2>&1 | tee error.log
+          if [ "${PIPESTATUS[0]}" -ne 0 ]; then
+            echo "yarn install failed."
+            exit 1
+          fi
 
       - name: Run test
         id: test
-        run: yarn test 2>&1 | tee error.log
+        run: |
+          yarn test 2>&1 | tee error.log
+          if [ "${PIPESTATUS[0]}" -ne 0 ]; then
+            echo "yarn test failed."
+            exit 1
+          fi
 
       - name: Print
         if: always()
