build failure

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -24,28 +24,17 @@ jobs:
           node-version: '16'
           cache: 'yarn'
 
-      - name: ls
-        run: ls -al
-
       - name: Install dependencies
         id: install_dependencies
-        run:
-          yarn install 2> >(tee error.log >&2) | tee /dev/null ; test ${PIPESTATUS[0]} -eq 0 || { echo "yarn install failed." >&2; exit 1; }
-          # yarn install 2> >(tee error.log >&2) | tee /dev/null
-          # if [ "${PIPESTATUS[0]}" -ne 0 ]; then
-          #   echo "yarn install failed." >&2
-          #   exit 1
-          # fi
+        run: yarn install 2> >(tee error.log >&2) | tee /dev/null ; test ${PIPESTATUS[0]} -eq 0 || { echo "yarn install failed." >&2; exit 1; }
+
+      - name: Run build
+        id: build
+        run: yarn build 2> >(tee error.log >&2) | tee /dev/null ; test ${PIPESTATUS[0]} -eq 0 || { echo "yarn build failed." >&2; exit 1; }
 
       - name: Run test
         id: test
-        run:
-          yarn test 2> >(tee error.log >&2) | tee /dev/null ; test ${PIPESTATUS[0]} -eq 0 || { echo "yarn test failed." >&2; exit 1; }
-          # yarn test 2> >(tee error.log >&2) | tee /dev/null
-          # if [ "${PIPESTATUS[0]}" -ne 0 ]; then
-          #   echo "yarn test failed." >&2
-          #   exit 1
-          # fi
+        run: yarn test 2> >(tee error.log >&2) | tee /dev/null ; test ${PIPESTATUS[0]} -eq 0 || { echo "yarn test failed." >&2; exit 1; }
 
       - name: Print
         if: always()
