temp

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -30,7 +30,18 @@ jobs:
 
       - name: Run build
         id: build
-        run: yarn build &> >(tee error_log) ; test ${PIPESTATUS[0]} -eq 0 || { echo "yarn build failed." ; exit 1; }
+        run: yarn build &> >(tee -a error_log) ; test ${PIPESTATUS[0]} -eq 0 || { echo "yarn build failed." ; exit 1; }
+        # run: yarn build &> >(tee error_log) ; test ${PIPESTATUS[0]} -eq 0 || { echo "yarn build failed." ; exit 1; }
+
+      - name: Temp Summary
+        if: ${{ failure() }}
+        run: |
+          echo '<details><summary>:boom: check line break</summary>' >> $GITHUB_STEP_SUMMARY
+          echo '' >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          echo '$(cat error_log)' >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          echo '</details>' >> $GITHUB_STEP_SUMMARY
 
       - name: Run test
         id: test
