handle error

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -29,11 +29,11 @@ jobs:
 
       - name: Install dependencies
         id: install_dependencies
-        run: yarn install 2> >(tee error.log >&2) | tee /dev/null || { echo "yarn test failed." >&2; exit 1; }
+        run: yarn install 2> >(tee error.log >&2) | tee /dev/null || { echo "::error::yarn start failed." }
 
       - name: Run test
         id: test
-        run: yarn test 2> >(tee error.log >&2) | tee /dev/null || { echo "yarn test failed." >&2; exit 1; }
+        run: yarn test 2> >(tee error.log >&2) | tee /dev/null || { echo "::error::yarn test failed." }
 
       - name: Print
         if: always()
