fail

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -29,11 +29,21 @@ jobs:
 
       - name: Install dependencies
         id: install_dependencies
-        run: yarn install 2> >(tee error.log >&2) | tee /dev/null || return 1
+        run: |
+          yarn install 2> >(tee error.log >&2) | tee /dev/null
+          if [ $? -ne 0 ]; then
+            echo "yarn install failed." >&2
+            exit 1
+          fi
 
       - name: Run test
         id: test
-        run: yarn test 2> >(tee error.log >&2) | tee /dev/null || return 1
+        run: |
+          yarn test 2> >(tee error.log >&2) | tee /dev/null
+          if [ $? -ne 0 ]; then
+            echo "yarn test failed." >&2
+            exit 1
+          fi
 
       - name: Print
         if: always()
